In [1]:
import numpy as np
from tqdm import trange

In [2]:
#given parameters
c = 0.055 #Coupon rate
T = 5  #Maturity
Call_Price = 103
stepsize = 0.5  #Semi-Annual
initial_rate = 0.06
u = 1.25
d = 1/u
q = 0.5
p = 1-q
N = int(T/stepsize)
price = 250*(1+c) #Price at maturity time

### **Compute Bond Price**

In [3]:
short_rate = np.zeros((N+1,N+1)) 
print(short_rate)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
short_rate[0][0] = initial_rate
print(short_rate)

[[0.06 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]]


In [5]:
for i in trange(len(short_rate)):
    for j in trange(len(short_rate)):
      if i > j :
          pass
      else:
          short_rate[i][j] =(u**i)*(d**(j-i))*initial_rate
print(short_rate)
del(i,j)

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 10998.17it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|██████████████████████████████████████████| 11/11 [00:00<00:00, 94.82it/s]

[[0.06       0.048      0.0384     0.03072    0.024576   0.0196608
  0.01572864 0.01258291 0.01006633 0.00805306 0.00644245]
 [0.         0.075      0.06       0.048      0.0384     0.03072
  0.024576   0.0196608  0.01572864 0.01258291 0.01006633]
 [0.         0.         0.09375    0.075      0.06       0.048
  0.0384     0.03072    0.024576   0.0196608  0.01572864]
 [0.         0.         0.         0.1171875  0.09375    0.075
  0.06       0.048      0.0384     0.03072    0.024576  ]
 [0.         0.         0.         0.         0.14648438 0.1171875
  0.09375    0.075      0.06       0.048      0.0384    ]
 [0.         0.         0.         0.         0.         0.18310547
  0.14648438 0.1171875  0.09375    0.075      0.06      ]
 [0.         0.         0.         0.         0.         0.
  0.22888184 0.18310547 0.14648438 0.1171875  0.09375   ]
 [0.         0.         0.         0.         0.         0.
  0.         0.28610229 0.22888184 0.18310547 0.14648438]
 [0.         0.        

In [6]:
Price = np.zeros((N+1,N+1))
print(Price)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
for i in trange(len(Price)-1,-1,-1):
    for j in trange(len(Price)-1,-1,-1):
      if i > j :
          pass
      else:
          if j == N:
              Price[i][j] = 250
          else:
              Price[i][j] = (q*Price[i+1][j+1] + p*Price[i][j+1])/(1+short_rate[i][j])
print(Price)
Bond_Price = Price[0][0]
print('Bond Price = {}'.format(round(Bond_Price,2)))

100%|████████████████████████████████████████| 11/11 [00:00<00:00, 5499.74it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 10998.17it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 10998.17it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 10998.17it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|████████████████████████████████████████| 11/11 [00:00<00:00, 5499.74it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████| 11/11 [00:00<00:00, 70.51it/s]

[[134.8328657  159.44908164 181.26927055 199.61512587 214.36630419
  225.78789765 234.34796443 240.57713592 244.98202027 248.00281752
  250.        ]
 [  0.         126.39659365 152.93600456 176.84489522 197.12830088
  213.48124331 226.10617226 235.49074248 242.22657342 246.89336255
  250.        ]
 [  0.           0.         118.8166718  147.37943445 173.5385995
  195.91481195 213.97260195 227.83517262 238.01478431 245.17957344
  250.        ]
 [  0.           0.           0.         112.53203511 143.32718456
  171.98701899 196.66484389 216.54312712 231.65375394 242.54889786
  250.        ]
 [  0.           0.           0.           0.         108.11158139
  141.54119723 173.10724694 200.38634193 222.2206405  238.54961832
  250.        ]
 [  0.           0.           0.           0.           0.
  106.3552804  143.14886562 178.28576075 208.60999466 232.55813953
  250.        ]
 [  0.           0.           0.           0.           0.
    0.         108.51016213 149.95011471 189.74725

### **Compute Callable Bond Price**

In [8]:
short_rate = np.zeros((N+1,N+1))
short_rate[0][0] = initial_rate
for i in trange(len(short_rate)):
    for j in trange(len(short_rate)):
      if i > j :
          pass
      else:
          short_rate[i][j] =(u**i)*(d**(j-i))*initial_rate
#print(short_rate)
del(i,j)

Price = np.zeros((N+1,N+1))
for i in trange(len(Price)-1,-1,-1):
    for j in trange(len(Price)-1,-1,-1):
      if i > j :
          pass
      else:
          if j == N:
              Price[i][j] = price
          else:
              Price[i][j] = 100*c + (q*Price[i+1][j+1] + p*Price[i][j+1])/(1+short_rate[i][j])
print(Price)
Bond_Price = Price[0][0]
Callable_Bond_Price = round(Bond_Price - Call_Price,2)
print('Callable Bond Price = {}'.format(Callable_Bond_Price))

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 10998.17it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 10995.55it/s]

100%|███████████████████████

[[184.74489714 209.25743766 229.75518614 245.70827079 257.1847851
  264.64249251 268.72347583 270.10306559 269.40121834 267.14297248
  263.75      ]
 [  0.         170.74174428 197.3204032  220.02489978 237.99015265
  251.09788824 259.75140663 264.62418065 266.46386702 265.97249749
  263.75      ]
 [  0.           0.         157.94934701 186.63435501 211.65403728
  231.73766077 246.5339041  256.37559775 261.97367166 264.16444998
  263.75      ]
 [  0.           0.           0.         146.84859158 177.78482598
  205.30889827 227.66023288 244.20361429 255.19132057 261.38908724
  263.75      ]
 [  0.           0.           0.           0.         138.04093332
  171.56415857 201.92889839 226.77607942 245.13145497 257.16984733
  263.75      ]
 [  0.           0.           0.           0.           0.
  132.34805964 169.12070591 202.91213581 230.61211579 250.84883721
  263.75      ]
 [  0.           0.           0.           0.           0.
    0.         131.0285602  172.2650297  210.48062