In [1]:
from __future__ import division
import sys
import math 
from scipy.optimize import fsolve
import pandas as pd
import numpy as np
from tqdm import trange

In [2]:
#given parameters
c = 0.055 #Coupon rate
T = 5  #Maturity
Call_Price = 103
stepsize = 0.5  #Semi-Annual
initial_rate = 0.06
u = 1.25
d = 1/u
q = 0.5
p = 1-q
N = int(T/stepsize)
price = 250*(1+c) #Price at maturity time

### **Compute Bond Price**

In [3]:
short_rate = np.zeros((N+1,N+1)) 
print(short_rate)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
short_rate[0][0] = initial_rate
print(short_rate)

[[0.06 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]]


In [5]:
for i in trange(len(short_rate)):
    for j in trange(len(short_rate)):
      if i > j :
          pass
      else:
          short_rate[i][j] =(u**i)*(d**(j-i))*initial_rate
print(short_rate)
del(i,j)

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 10998.17it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 10998.17it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|█████████████████████████████████████████| 11/11 [00:00<00:00, 114.58it/s]

[[0.06       0.048      0.0384     0.03072    0.024576   0.0196608
  0.01572864 0.01258291 0.01006633 0.00805306 0.00644245]
 [0.         0.075      0.06       0.048      0.0384     0.03072
  0.024576   0.0196608  0.01572864 0.01258291 0.01006633]
 [0.         0.         0.09375    0.075      0.06       0.048
  0.0384     0.03072    0.024576   0.0196608  0.01572864]
 [0.         0.         0.         0.1171875  0.09375    0.075
  0.06       0.048      0.0384     0.03072    0.024576  ]
 [0.         0.         0.         0.         0.14648438 0.1171875
  0.09375    0.075      0.06       0.048      0.0384    ]
 [0.         0.         0.         0.         0.         0.18310547
  0.14648438 0.1171875  0.09375    0.075      0.06      ]
 [0.         0.         0.         0.         0.         0.
  0.22888184 0.18310547 0.14648438 0.1171875  0.09375   ]
 [0.         0.         0.         0.         0.         0.
  0.         0.28610229 0.22888184 0.18310547 0.14648438]
 [0.         0.        

In [6]:
Price = np.zeros((N+1,N+1))
print(Price)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
for i in trange(len(Price)-1,-1,-1):
    for j in trange(len(Price)-1,-1,-1):
      if i > j :
          pass
      else:
          if j == N:
              Price[i][j] = 250
          else:
              Price[i][j] = (q*Price[i+1][j+1] + p*Price[i][j+1])/(1+short_rate[i][j])
print(Price)
Bond_Price = Price[0][0]
print('Bond Price = {}'.format(round(Bond_Price,2)))

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|███████████████████████████████████████| 11/11 [00:00<00:00, 11000.80it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|█████████████████████████████████████████| 11/11 [00:00<00:00, 127.90it/s]

[[134.8328657  159.44908164 181.26927055 199.61512587 214.36630419
  225.78789765 234.34796443 240.57713592 244.98202027 248.00281752
  250.        ]
 [  0.         126.39659365 152.93600456 176.84489522 197.12830088
  213.48124331 226.10617226 235.49074248 242.22657342 246.89336255
  250.        ]
 [  0.           0.         118.8166718  147.37943445 173.5385995
  195.91481195 213.97260195 227.83517262 238.01478431 245.17957344
  250.        ]
 [  0.           0.           0.         112.53203511 143.32718456
  171.98701899 196.66484389 216.54312712 231.65375394 242.54889786
  250.        ]
 [  0.           0.           0.           0.         108.11158139
  141.54119723 173.10724694 200.38634193 222.2206405  238.54961832
  250.        ]
 [  0.           0.           0.           0.           0.
  106.3552804  143.14886562 178.28576075 208.60999466 232.55813953
  250.        ]
 [  0.           0.           0.           0.           0.
    0.         108.51016213 149.95011471 189.74725

### **Compute Callable Bond Price**

In [8]:
"""
Maturity            Yield(%)       Yield_Volatility
1                    10             21
2                    10.5           20
3                    11             19
4                    11.5           18
5                    12             17
6                    12.5           16
7                    13             15
8                    13.5           14
9                    14             13
10                   14.5           12
11                   15             11
"""
t = [1,2,3,4,5,6,7,8,9,10,11]        
r = [0.1,0.105,0.11,0.115,0.12,0.125,0.13,0.135,0.14,0.145,0.15]
vol = [0.21,0.20,0.19,0.18,0.17,0.16,0.15,0.14,0.13,0.12,0.11]
df  = pd.DataFrame(data={'t':t,'Yield':r,'Vol':vol})
m = 0.03  #guess
a1 = 100/(1+r[0])**1
a2 = 100/(1+r[1])**2
a3 = 100/(1+r[2])**3
a4 = 100/(1+r[3])**4
a5 = 100/(1+r[4])**5
a6 = 100/(1+r[5])**6
a7 = 100/(1+r[6])**7
a8 = 100/(1+r[7])**8
a9 = 100/(1+r[8])**9
a10 = 100/(1+r[9])**10
a11 = 100/(1+r[10])**11

In [9]:
def bdtOne(guess):
    r_u = guess * math.exp(2 * df.Vol.iloc[1])
    r_d = guess 
    N1 = (100)/(1+r_u)
    N2 = (100)/(1+r_d)
    return (0.5*((N1/(1+r[0])) + (N2/(1+r[0])))-a2)
    
g = fsolve(bdtOne,m)[0]
r_u = g * math.exp(2 * df.Vol.iloc[1])
r_d = g

In [10]:
def bdtTwo2(x):
    r_u2 = x[0] * math.exp(4 * x[1])
    r_ud = x[0] * math.exp(2 * x[1])
    r_d2 = x[0]
    N1 = (100)/(1+r_u2)
    N2 = (100)/(1+r_ud)
    N3 = (100)/(1+r_d2)
    ans1 = (0.5*(N1 + N2))/(1+r_u)
    ans2 = (0.5*(N2 + N3))/(1+r_d)
    y_u = math.sqrt(100/ans1) - 1
    y_d = math.sqrt(100/ans2) - 1
    out = [((0.5*(ans1 + ans2))/(1+r[0])-a3)]
    out.append((0.5 * math.log(y_u/y_d) - df.Vol.iloc[2]))
    return out

k = fsolve(bdtTwo2,[0.1,0.1])
r_u2 = k[0] * math.exp(4 * k[1])
r_ud = k[0] * math.exp(2 * k[1])
r_d2 = k[0]

In [11]:
def bdtThree3(x):
    r_u3 = x[0] * math.exp(6 * x[1])
    r_u2d = x[0] * math.exp(4 * x[1])
    r_ud3 = x[0] * math.exp(2 * x[1])
    r_d4 = x[0]
    N1 = 100/(1+r_u3) 
    N2 = 100/(1+r_u2d)
    N3 = 100/(1+r_ud3)
    N4 = 100/(1+r_d4)
    ans1 = (0.5*(N1+N2))/(1+r_u2)
    ans2 = (0.5*(N2+N3))/(1+r_ud)
    ans3 = (0.5*(N3+N4))/(1+r_d2)
    fans1 = (0.5*(ans1+ans2))/(1+r_u)
    fans2 = (0.5*(ans2+ans3))/(1+r_d)
    y_u2 = math.sqrt(100/ans1) - 1
    y_ud = math.sqrt(100/ans2) - 1
    y_d2 = math.sqrt(100/ans3) - 1
    out = [((0.5*fans1 + 0.5*fans2)/(1+r[0]) - a4)]
    out.append((0.5 * math.log(y_u2/y_ud) - df.Vol.iloc[3] )) 
    return out

g = fsolve(bdtThree3,[0.1,0.1],xtol=1.49012e-20 )
#bdtThree3([ 0.08271889,  0.16859304])
r_u3 = g[0] * math.exp(6 * g[1])
r_u2d = g[0] * math.exp(4 * g[1])
r_ud2 = g[0] * math.exp(2 * g[1])
r_d3 = g[0]

C:\Users\TOT_User\anaconda3\lib\site-packages\scipy\optimize\_minpack_py.py:175: RuntimeWarning: xtol=0.000000 is too small, no further improvement in the approximate
  solution is possible.
  warnings.warn(msg, RuntimeWarning)


In [12]:
def bdtFour(x):
    r_u4 = x[0]*math.exp(8 * x[1] )
    r_u3d = x[0]*math.exp(6 * x[1])
    r_u2d2 = x[0]*math.exp(4 * x[1])
    r_ud3 = x[0]*math.exp(2 * x[1])
    r_d4 = x[0]  
    N1 = 100/(1+r_u4) 
    N2 = 100/(1+r_u3d)
    N3 = 100/(1+r_u2d2)
    N4 = 100/(1+r_ud3)
    N5 = 100/(1+r_d4)
    ans1 = (0.5*(N1+N2))/(1+r_u3)
    ans2 = (0.5*(N2+N3))/(1+r_u2d)
    ans3 = (0.5*(N3+N4))/(1+r_ud2)
    ans4 = (0.5*(N4+N5))/(1+r_d3)
    fans1 = ((0.5*ans1 + 0.5*ans2))/(1 + r_u2)
    fans2 = ((0.5*ans2 + 0.5*ans3))/(1 + r_ud)
    fans3 = ((0.5*ans3 + 0.5*ans4))/(1 + r_d2)
    xans1 = ((0.5*fans1 + 0.5*fans2))/(1 + r_u)
    xans2 = ((0.5*fans2 + 0.5*fans3))/(1 + r_d)
    y_u3 = math.sqrt(100/ans1) - 1
    y_u2d = math.sqrt(100/ans2) - 1
    y_ud2 = math.sqrt(100/ans3) - 1
    y_d3 = math.sqrt(100/ans4) - 1
    out = [((0.5*xans1 + 0.5*xans2)/(1+r[0]) -a5 )]
    out.append(((0.5 * math.log(y_u3/y_u2d) - df.Vol.iloc[4])))    
    return out

g = fsolve(bdtFour,[0.1,0.1],xtol=1.49012e-20)
#bdtFour([ 0.08048839,  0.15227017])
r_u4 = g[0] * math.exp(8 * g[1])
r_u3d = g[0] * math.exp(6 * g[1])
r_u2d2 = g[0] * math.exp(4 * g[1])
r_ud3 = g[0] * math.exp(2 * g[1])
r_d4 = g[0] 

In [13]:
def bdtFive(x):
    r_u5 = x[0]*math.exp(10 * x[1] )
    r_u4d = x[0]*math.exp(8 * x[1] ) 
    r_u3d2 = x[0]*math.exp(6 * x[1]) 
    r_u2d3 = x[0]*math.exp(4 * x[1])
    r_ud4 = x[0]*math.exp(2 * x[1])    
    r_d5 = x[0]  
    N1 = 100/(1+r_u5) 
    N2 = 100/(1+r_u4d)
    N3 = 100/(1+r_u3d2)
    N4 = 100/(1+r_u2d3)
    N5 = 100/(1+r_ud4)
    N6 = 100/(1+r_d5)
    ans1 = (0.5*(N1+N2))/(1+r_u4)
    ans2 = (0.5*(N2+N3))/(1+r_u3d)
    ans3 = (0.5*(N3+N4))/(1+r_u2d2)
    ans4 = (0.5*(N4+N5))/(1+r_ud3)
    ans5 = (0.5*(N5+N6))/(1+r_d4)
    fans1 = (0.5*(ans1+ans2))/(1+r_u3)
    fans2 = (0.5*(ans2+ans3))/(1+r_u2d)
    fans3 = (0.5*(ans3+ans4))/(1+r_ud2)
    fans4 = (0.5*(ans4+ans5))/(1+r_d3)
    xans1 = (0.5*(fans1+fans2))/(1+r_u2)
    xans2 = (0.5*(fans2+fans3))/(1+r_ud)
    xans3 = (0.5*(fans3+fans4))/(1+r_d2)
    a4ans1 = (0.5*(xans1+xans2))/(1+r_u)
    a4ans2 = (0.5*(xans2+xans3))/(1+r_d)
    y_u4 = math.sqrt(100/ans1) - 1
    y_u3d = math.sqrt(100/ans2) - 1
    y_u2d2 = math.sqrt(100/ans3) - 1
    y_ud3 = math.sqrt(100/ans4) - 1
    y_d4 = math.sqrt(100/ans5) - 1
    out = [((0.5*a4ans1 + 0.5*a4ans2)/(1+r[0]) -a6 )]
    out.append(((0.5 * math.log(y_u4/y_u3d) - df.Vol.iloc[5])))    
    return out

g = fsolve(bdtFive,[0.1,0.1],xtol=1.49012e-20)
r_u5 = g[0] * math.exp(10 * g[1])
r_u4d = g[0] * math.exp(8 * g[1])
r_u3d2 = g[0] * math.exp(6 * g[1])
r_u2d3 = g[0] * math.exp(4 * g[1])
r_ud4 = g[0] * math.exp(2 * g[1]) 
r_d5 = g[0]

In [14]:
def bdtSix(x):
    r_u6 = x[0]*math.exp(12 * x[1] )    
    r_u5d = x[0]*math.exp(10 * x[1] )
    r_u4d2 = x[0]*math.exp(8 * x[1] ) 
    r_u3d3 = x[0]*math.exp(6 * x[1]) 
    r_u2d4 = x[0]*math.exp(4 * x[1])
    r_ud5 = x[0]*math.exp(2 * x[1])    
    r_d6 = x[0]  
    N1 = 100/(1+r_u6) 
    N2 = 100/(1+r_u5d)
    N3 = 100/(1+r_u4d2)
    N4 = 100/(1+r_u3d3)
    N5 = 100/(1+r_u2d4)
    N6 = 100/(1+r_ud5)
    N7 = 100/(1+r_d6)
    ans1 = (0.5*(N1+N2))/(1+r_u5)
    ans2 = (0.5*(N2+N3))/(1+r_u4d)
    ans3 = (0.5*(N3+N4))/(1+r_u3d2)
    ans4 = (0.5*(N4+N5))/(1+r_u2d3)
    ans5 = (0.5*(N5+N6))/(1+r_ud4)
    ans6 = (0.5*(N6+N7))/(1+r_d5)
    fans1 = (0.5*(ans1+ans2))/(1+r_u4)
    fans2 = (0.5*(ans2+ans3))/(1+r_u3d)
    fans3 = (0.5*(ans3+ans4))/(1+r_u2d2)
    fans4 = (0.5*(ans4+ans5))/(1+r_ud3)
    fans5 = (0.5*(ans5+ans6))/(1+r_d4)
    xans1 = (0.5*(fans1+fans2))/(1+r_u3)
    xans2 = (0.5*(fans2+fans3))/(1+r_u2d)
    xans3 = (0.5*(fans3+fans4))/(1+r_ud2)
    xans4 = (0.5*(fans4+fans5))/(1+r_d3)
    a4ans1 = (0.5*(xans1+xans2))/(1+r_u2)
    a4ans2 = (0.5*(xans2+xans3))/(1+r_ud)
    a4ans3 = (0.5*(xans3+xans4))/(1+r_d2)
    a5ans1 = (0.5*(a4ans1+a4ans2))/(1+r_u)
    a5ans2 = (0.5*(a4ans2+a4ans3))/(1+r_d)
    y_u5 = math.sqrt(100/ans1) - 1
    y_u4d = math.sqrt(100/ans2) - 1
    y_u3d2 = math.sqrt(100/ans3) - 1
    y_u2d3 = math.sqrt(100/ans4) - 1
    y_ud4 = math.sqrt(100/ans5) - 1
    y_d5 = math.sqrt(100/ans6) - 1
    out = [((0.5*a5ans1 + 0.5*a5ans2)/(1+r[0]) -a7 )]
    out.append(((0.5 * math.log(y_u5/y_u4d) - df.Vol.iloc[6])))    
    return out

g = fsolve(bdtSix,[0.1,0.1],xtol=1.49012e-20)
#bdtFour([ 0.08048839,  0.15227017])
r_u6 = g[0] * math.exp(12 * g[1])
r_u5d = g[0] * math.exp(10 * g[1])
r_u4d2 = g[0] * math.exp(8 * g[1])
r_u3d3 = g[0] * math.exp(6 * g[1])
r_u2d4 = g[0] * math.exp(4 * g[1])
r_ud5 = g[0] * math.exp(2 * g[1]) 
r_d6 = g[0]

In [15]:
def bdtSeven(x):
    r_u7 = x[0]*math.exp(14 * x[1] )
    r_u6d = x[0]*math.exp(12 * x[1] )    
    r_u5d2 = x[0]*math.exp(10 * x[1] )
    r_u4d3 = x[0]*math.exp(8 * x[1] ) 
    r_u3d4 = x[0]*math.exp(6 * x[1]) 
    r_u2d5 = x[0]*math.exp(4 * x[1])
    r_ud6 = x[0]*math.exp(2 * x[1])    
    r_d7 = x[0]  
    N1 = 100/(1+r_u7) 
    N2 = 100/(1+r_u6d)
    N3 = 100/(1+r_u5d2)
    N4 = 100/(1+r_u4d3)
    N5 = 100/(1+r_u3d4)
    N6 = 100/(1+r_u2d5)
    N7 = 100/(1+r_ud6)
    N8 = 100/(1+r_d7)
    ans1 = (0.5*(N1+N2))/(1+r_u6)
    ans2 = (0.5*(N2+N3))/(1+r_u5d)
    ans3 = (0.5*(N3+N4))/(1+r_u4d2)
    ans4 = (0.5*(N4+N5))/(1+r_u3d3)
    ans5 = (0.5*(N5+N6))/(1+r_u2d4)
    ans6 = (0.5*(N6+N7))/(1+r_ud5)
    ans7 = (0.5*(N7+N8))/(1+r_d6)
    fans1 = (0.5*(ans1+ans2))/(1+r_u5)
    fans2 = (0.5*(ans2+ans3))/(1+r_u4d)
    fans3 = (0.5*(ans3+ans4))/(1+r_u3d2)
    fans4 = (0.5*(ans4+ans5))/(1+r_u2d3)
    fans5 = (0.5*(ans5+ans6))/(1+r_ud4)
    fans6 = (0.5*(ans6+ans7))/(1+r_d5)
    xans1 = (0.5*(fans1+fans2))/(1+r_u4)
    xans2 = (0.5*(fans2+fans3))/(1+r_u3d)
    xans3 = (0.5*(fans3+fans4))/(1+r_u2d2)
    xans4 = (0.5*(fans4+fans5))/(1+r_ud3)
    xans5 = (0.5*(fans5+fans6))/(1+r_d4)
    a4ans1 = (0.5*(xans1+xans2))/(1+r_u3)
    a4ans2 = (0.5*(xans2+xans3))/(1+r_u2d)
    a4ans3 = (0.5*(xans3+xans4))/(1+r_ud2)
    a4ans4 = (0.5*(xans4+xans5))/(1+r_d3)
    a5ans1 = (0.5*(a4ans1+a4ans2))/(1+r_u2)
    a5ans2 = (0.5*(a4ans2+a4ans3))/(1+r_ud)
    a5ans3 = (0.5*(a4ans3+a4ans4))/(1+r_d2)
    a6ans1 = (0.5*(a5ans1+a5ans2))/(1+r_u)
    a6ans2 = (0.5*(a5ans2+a5ans3))/(1+r_d)
    y_u6 = math.sqrt(100/ans1) - 1
    y_u5d = math.sqrt(100/ans2) - 1
    y_u4d2 = math.sqrt(100/ans3) - 1
    y_u3d3 = math.sqrt(100/ans4) - 1
    y_u2d4 = math.sqrt(100/ans5) - 1
    y_ud5 = math.sqrt(100/ans6) - 1
    y_d6 = math.sqrt(100/ans7) - 1
    out = [((0.5*a6ans1 + 0.5*a6ans2)/(1+r[0]) -a8 )]
    out.append(((0.5 * math.log(y_u6/y_u5d) - df.Vol.iloc[7])))    
    return out

g = fsolve(bdtSeven,[0.1,0.1],xtol=1.49012e-20)
r_u7 = g[0] * math.exp(14 * g[1])
r_u6d = g[0] * math.exp(12 * g[1])
r_u5d2 = g[0] * math.exp(10 * g[1])
r_u4d3 = g[0] * math.exp(8 * g[1])
r_u3d4 = g[0] * math.exp(6 * g[1])
r_u2d5 = g[0] * math.exp(4 * g[1])
r_ud6 = g[0] * math.exp(2 * g[1]) 
r_d7 = g[0]

In [16]:
def bdtEight(x):
    r_u8 = x[0]*math.exp(16 * x[1] )
    r_u7d = x[0]*math.exp(14 * x[1] )
    r_u6d2 = x[0]*math.exp(12 * x[1] )    
    r_u5d3 = x[0]*math.exp(10 * x[1] )
    r_u4d4 = x[0]*math.exp(8 * x[1] ) 
    r_u3d5 = x[0]*math.exp(6 * x[1]) 
    r_u2d6 = x[0]*math.exp(4 * x[1])
    r_ud7 = x[0]*math.exp(2 * x[1])    
    r_d8 = x[0]  
    N1 = 100/(1+r_u8) 
    N2 = 100/(1+r_u7d)
    N3 = 100/(1+r_u6d2)
    N4 = 100/(1+r_u5d3)
    N5 = 100/(1+r_u4d4)
    N6 = 100/(1+r_u3d5)
    N7 = 100/(1+r_u2d6)
    N8 = 100/(1+r_ud7)
    N9 = 100/(1+r_d8)
    ans1 = (0.5*(N1+N2))/(1+r_u7)
    ans2 = (0.5*(N2+N3))/(1+r_u6d)
    ans3 = (0.5*(N3+N4))/(1+r_u5d2)
    ans4 = (0.5*(N4+N5))/(1+r_u4d3)
    ans5 = (0.5*(N5+N6))/(1+r_u3d4)
    ans6 = (0.5*(N6+N7))/(1+r_u2d5)
    ans7 = (0.5*(N7+N8))/(1+r_ud6)
    ans8 = (0.5*(N8+N9))/(1+r_d7)
    fans1 = (0.5*(ans1+ans2))/(1+r_u6)
    fans2 = (0.5*(ans2+ans3))/(1+r_u5d)
    fans3 = (0.5*(ans3+ans4))/(1+r_u4d2)
    fans4 = (0.5*(ans4+ans5))/(1+r_u3d3)
    fans5 = (0.5*(ans5+ans6))/(1+r_u2d4)
    fans6 = (0.5*(ans6+ans7))/(1+r_ud5)
    fans7= (0.5*(ans7+ans8))/(1+r_d6)
    xans1 = (0.5*(fans1+fans2))/(1+r_u5)
    xans2 = (0.5*(fans2+fans3))/(1+r_u4d)
    xans3 = (0.5*(fans3+fans4))/(1+r_u3d2)
    xans4 = (0.5*(fans4+fans5))/(1+r_u2d3)
    xans5 = (0.5*(fans5+fans6))/(1+r_ud4)
    xans6 = (0.5*(fans6+fans7))/(1+r_d5)
    a4ans1 = (0.5*(xans1+xans2))/(1+r_u4)
    a4ans2 = (0.5*(xans2+xans3))/(1+r_u3d)
    a4ans3 = (0.5*(xans3+xans4))/(1+r_u2d2)
    a4ans4 = (0.5*(xans4+xans5))/(1+r_ud3)
    a4ans5 = (0.5*(xans5+xans6))/(1+r_d4)
    a5ans1 = (0.5*(a4ans1+a4ans2))/(1+r_u3)
    a5ans2 = (0.5*(a4ans2+a4ans3))/(1+r_u2d)
    a5ans3 = (0.5*(a4ans3+a4ans4))/(1+r_ud2)
    a5ans4 = (0.5*(a4ans4+a4ans5))/(1+r_d3)
    a6ans1 = (0.5*(a5ans1+a5ans2))/(1+r_u2)
    a6ans2 = (0.5*(a5ans2+a5ans3))/(1+r_ud)
    a6ans3 = (0.5*(a5ans3+a5ans4))/(1+r_d2)
    a7ans1 = (0.5*(a6ans1+a6ans2))/(1+r_u)
    a7ans2 = (0.5*(a6ans2+a6ans3))/(1+r_d)
    y_u7 = math.sqrt(100/ans1) - 1
    y_u6d = math.sqrt(100/ans2) - 1
    y_u5d2 = math.sqrt(100/ans3) - 1
    y_u4d3 = math.sqrt(100/ans4) - 1
    y_u3d4 = math.sqrt(100/ans5) - 1
    y_u2d5 = math.sqrt(100/ans6) - 1
    y_ud6 = math.sqrt(100/ans7) - 1
    y_d7 = math.sqrt(100/ans8) - 1
    out = [((0.5*a7ans1 + 0.5*a7ans2)/(1+r[0]) -a9 )]
    out.append(((0.5 * math.log(y_u7/y_u6d) - df.Vol.iloc[8])))    
    return out

g = fsolve(bdtEight,[0.1,0.1],xtol=1.49012e-20)
r_u8 = g[0] * math.exp(16 * g[1])
r_u7d = g[0] * math.exp(14 * g[1])
r_u6d2 = g[0] * math.exp(12 * g[1])
r_u5d3 = g[0] * math.exp(10 * g[1])
r_u4d4 = g[0] * math.exp(8 * g[1])
r_u3d5 = g[0] * math.exp(6 * g[1])
r_u2d6 = g[0] * math.exp(4 * g[1])
r_ud7 = g[0] * math.exp(2 * g[1]) 
r_d8 = g[0]

C:\Users\TOT_User\anaconda3\lib\site-packages\scipy\optimize\_minpack_py.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)


In [17]:
def bdtNine(x):
    r_u9 = x[0]*math.exp(18 * x[1] )
    r_u8d = x[0]*math.exp(16 * x[1] )
    r_u7d2 = x[0]*math.exp(14 * x[1] )
    r_u6d3 = x[0]*math.exp(12 * x[1] )    
    r_u5d4 = x[0]*math.exp(10 * x[1] )
    r_u4d5 = x[0]*math.exp(8 * x[1] ) 
    r_u3d6 = x[0]*math.exp(6 * x[1]) 
    r_u2d7 = x[0]*math.exp(4 * x[1])
    r_ud8 = x[0]*math.exp(2 * x[1])    
    r_d9 = x[0]  
    N1 = 100/(1+r_u9) 
    N2 = 100/(1+r_u8d)
    N3 = 100/(1+r_u7d2)
    N4 = 100/(1+r_u6d3)
    N5 = 100/(1+r_u5d4)
    N6 = 100/(1+r_u4d5)
    N7 = 100/(1+r_u3d6)
    N8 = 100/(1+r_u2d7)
    N9 = 100/(1+r_ud8)
    N10 = 100/(1+r_d9)
    ans1 = (0.5*(N1+N2))/(1+r_u8)
    ans2 = (0.5*(N2+N3))/(1+r_u7d)
    ans3 = (0.5*(N3+N4))/(1+r_u6d2)
    ans4 = (0.5*(N4+N5))/(1+r_u5d3)
    ans5 = (0.5*(N5+N6))/(1+r_u4d4)
    ans6 = (0.5*(N6+N7))/(1+r_u3d5)
    ans7 = (0.5*(N7+N8))/(1+r_u2d6)
    ans8 = (0.5*(N8+N9))/(1+r_ud7)
    ans9 = (0.5*(N9+N10))/(1+r_d8)
    fans1 = (0.5*(ans1+ans2))/(1+r_u7)
    fans2 = (0.5*(ans2+ans3))/(1+r_u6d)
    fans3 = (0.5*(ans3+ans4))/(1+r_u5d2)
    fans4 = (0.5*(ans4+ans5))/(1+r_u4d3)
    fans5 = (0.5*(ans5+ans6))/(1+r_u3d4)
    fans6 = (0.5*(ans6+ans7))/(1+r_u2d5)
    fans7= (0.5*(ans7+ans8))/(1+r_ud6)
    fans8= (0.5*(ans8+ans9))/(1+r_d7)
    xans1 = (0.5*(fans1+fans2))/(1+r_u6)
    xans2 = (0.5*(fans2+fans3))/(1+r_u5d)
    xans3 = (0.5*(fans3+fans4))/(1+r_u4d2)
    xans4 = (0.5*(fans4+fans5))/(1+r_u3d3)
    xans5 = (0.5*(fans5+fans6))/(1+r_u2d4)
    xans6 = (0.5*(fans6+fans7))/(1+r_ud5)
    xans7 = (0.5*(fans7+fans8))/(1+r_d6)
    a4ans1 = (0.5*(xans1+xans2))/(1+r_u5)
    a4ans2 = (0.5*(xans2+xans3))/(1+r_u4d)
    a4ans3 = (0.5*(xans3+xans4))/(1+r_u3d2)
    a4ans4 = (0.5*(xans4+xans5))/(1+r_u2d3)
    a4ans5 = (0.5*(xans5+xans6))/(1+r_ud4)
    a4ans6 = (0.5*(xans6+xans7))/(1+r_d5)
    a5ans1 = (0.5*(a4ans1+a4ans2))/(1+r_u4)
    a5ans2 = (0.5*(a4ans2+a4ans3))/(1+r_u3d)
    a5ans3 = (0.5*(a4ans3+a4ans4))/(1+r_u2d2)
    a5ans4 = (0.5*(a4ans4+a4ans5))/(1+r_ud3)
    a5ans5 = (0.5*(a4ans5+a4ans6))/(1+r_d4)
    a6ans1 = (0.5*(a5ans1+a5ans2))/(1+r_u3)
    a6ans2 = (0.5*(a5ans2+a5ans3))/(1+r_u2d)
    a6ans3 = (0.5*(a5ans3+a5ans4))/(1+r_ud2)
    a6ans4 = (0.5*(a5ans4+a5ans5))/(1+r_d3)
    a7ans1 = (0.5*(a6ans1+a6ans2))/(1+r_u2)
    a7ans2 = (0.5*(a6ans2+a6ans3))/(1+r_ud)
    a7ans3 = (0.5*(a6ans3+a6ans4))/(1+r_d2)
    a8ans1 = (0.5*(a7ans1+a7ans2))/(1+r_u)
    a8ans2 = (0.5*(a7ans2+a7ans3))/(1+r_d)
    y_u8 = math.sqrt(100/ans1) - 1
    y_u7d = math.sqrt(100/ans2) - 1
    y_u6d2 = math.sqrt(100/ans3) - 1
    y_u5d3 = math.sqrt(100/ans4) - 1
    y_u4d4 = math.sqrt(100/ans5) - 1
    y_u3d5 = math.sqrt(100/ans6) - 1
    y_u2d6 = math.sqrt(100/ans7) - 1
    y_ud7 = math.sqrt(100/ans8) - 1
    y_d7 = math.sqrt(100/ans9) - 1
    out = [((0.5*a8ans1 + 0.5*a8ans2)/(1+r[0]) -a10 )]
    out.append(((0.5 * math.log(y_u8/y_u7d) - df.Vol.iloc[9])))    
    return out

g = fsolve(bdtNine,[0.1,0.1],xtol=1.49012e-20)
r_u9 = g[0] * math.exp(18 * g[1]) 
r_u8d = g[0] * math.exp(16 * g[1])
r_u7d2 = g[0] * math.exp(14 * g[1])
r_u6d3 = g[0] * math.exp(12 * g[1])
r_u5d4 = g[0] * math.exp(10 * g[1])
r_u4d5 = g[0] * math.exp(8 * g[1])
r_u3d6 = g[0] * math.exp(6 * g[1])
r_u2d7 = g[0] * math.exp(4 * g[1])
r_ud8 = g[0] * math.exp(2 * g[1]) 
r_d9 = g[0]

In [18]:
def bdtTen(x):
    r_u10 = x[0]*math.exp(20 * x[1] )
    r_u9d = x[0]*math.exp(18 * x[1] )
    r_u8d2 = x[0]*math.exp(16 * x[1] )
    r_u7d3 = x[0]*math.exp(14 * x[1] )
    r_u6d4 = x[0]*math.exp(12 * x[1] )    
    r_u5d5 = x[0]*math.exp(10 * x[1] )
    r_u4d6 = x[0]*math.exp(8 * x[1] ) 
    r_u3d7 = x[0]*math.exp(6 * x[1]) 
    r_u2d8 = x[0]*math.exp(4 * x[1])
    r_ud9 = x[0]*math.exp(2 * x[1])    
    r_d10 = x[0]  
    N1 = 100/(1+r_u10) 
    N2 = 100/(1+r_u9d)
    N3 = 100/(1+r_u8d2)
    N4 = 100/(1+r_u7d3)
    N5 = 100/(1+r_u6d4)
    N6 = 100/(1+r_u5d5)
    N7 = 100/(1+r_u4d6)
    N8 = 100/(1+r_u3d7)
    N9 = 100/(1+r_u2d8)
    N10 = 100/(1+r_ud9)
    N11 = 100/(1+r_d10)
    ans1 = (0.5*(N1+N2))/(1+r_u9)
    ans2 = (0.5*(N2+N3))/(1+r_u8d)
    ans3 = (0.5*(N3+N4))/(1+r_u7d2)
    ans4 = (0.5*(N4+N5))/(1+r_u6d3)
    ans5 = (0.5*(N5+N6))/(1+r_u5d4)
    ans6 = (0.5*(N6+N7))/(1+r_u4d5)
    ans7 = (0.5*(N7+N8))/(1+r_u3d6)
    ans8 = (0.5*(N8+N9))/(1+r_u2d7)
    ans9 = (0.5*(N9+N10))/(1+r_ud8)
    ans10 = (0.5*(N10+N11))/(1+r_d9)
    fans1 = (0.5*(ans1+ans2))/(1+r_u8)
    fans2 = (0.5*(ans2+ans3))/(1+r_u7d)
    fans3 = (0.5*(ans3+ans4))/(1+r_u6d2)
    fans4 = (0.5*(ans4+ans5))/(1+r_u5d3)
    fans5 = (0.5*(ans5+ans6))/(1+r_u4d4)
    fans6 = (0.5*(ans6+ans7))/(1+r_u3d5)
    fans7= (0.5*(ans7+ans8))/(1+r_u2d6)
    fans8= (0.5*(ans8+ans9))/(1+r_ud7)
    fans9= (0.5*(ans9+ans10))/(1+r_d8)
    xans1 = (0.5*(fans1+fans2))/(1+r_u7)
    xans2 = (0.5*(fans2+fans3))/(1+r_u6d)
    xans3 = (0.5*(fans3+fans4))/(1+r_u5d2)
    xans4 = (0.5*(fans4+fans5))/(1+r_u4d3)
    xans5 = (0.5*(fans5+fans6))/(1+r_u3d4)
    xans6 = (0.5*(fans6+fans7))/(1+r_u2d5)
    xans7 = (0.5*(fans7+fans8))/(1+r_ud6)
    xans8 = (0.5*(fans8+fans9))/(1+r_d7)
    a4ans1 = (0.5*(xans1+xans2))/(1+r_u6)
    a4ans2 = (0.5*(xans2+xans3))/(1+r_u5d)
    a4ans3 = (0.5*(xans3+xans4))/(1+r_u4d2)
    a4ans4 = (0.5*(xans4+xans5))/(1+r_u3d3)
    a4ans5 = (0.5*(xans5+xans6))/(1+r_u2d4)
    a4ans6 = (0.5*(xans6+xans7))/(1+r_ud5)
    a4ans7 = (0.5*(xans7+xans8))/(1+r_d6)
    a5ans1 = (0.5*(a4ans1+a4ans2))/(1+r_u5)
    a5ans2 = (0.5*(a4ans2+a4ans3))/(1+r_u4d)
    a5ans3 = (0.5*(a4ans3+a4ans4))/(1+r_u3d2)
    a5ans4 = (0.5*(a4ans4+a4ans5))/(1+r_u2d3)
    a5ans5 = (0.5*(a4ans5+a4ans6))/(1+r_ud4)
    a5ans6 = (0.5*(a4ans6+a4ans7))/(1+r_d5)
    a6ans1 = (0.5*(a5ans1+a5ans2))/(1+r_u4)
    a6ans2 = (0.5*(a5ans2+a5ans3))/(1+r_u3d)
    a6ans3 = (0.5*(a5ans3+a5ans4))/(1+r_u2d2)
    a6ans4 = (0.5*(a5ans4+a5ans5))/(1+r_ud3)
    a6ans5 = (0.5*(a5ans5+a5ans6))/(1+r_d4)
    a7ans1 = (0.5*(a6ans1+a6ans2))/(1+r_u3)
    a7ans2 = (0.5*(a6ans2+a6ans3))/(1+r_u2d)
    a7ans3 = (0.5*(a6ans3+a6ans4))/(1+r_ud2)
    a7ans4 = (0.5*(a6ans4+a6ans5))/(1+r_d3)
    a8ans1 = (0.5*(a7ans1+a7ans2))/(1+r_u2)
    a8ans2 = (0.5*(a7ans2+a7ans3))/(1+r_ud)
    a8ans3 = (0.5*(a7ans3+a7ans4))/(1+r_d2)
    a9ans1 = (0.5*(a8ans1+a8ans2))/(1+r_u)
    a9ans2 = (0.5*(a8ans2+a8ans3))/(1+r_d)
    y_u9 = math.sqrt(100/ans1) - 1
    y_u8d = math.sqrt(100/ans2) - 1
    y_u7d2 = math.sqrt(100/ans3) - 1
    y_u6d3 = math.sqrt(100/ans4) - 1
    y_u5d4 = math.sqrt(100/ans5) - 1
    y_u4d5 = math.sqrt(100/ans6) - 1
    y_u3d6 = math.sqrt(100/ans7) - 1
    y_u2d7 = math.sqrt(100/ans8) - 1
    y_ud8 = math.sqrt(100/ans9) - 1
    y_d9 = math.sqrt(100/ans10) - 1
    out = [((0.5*a9ans1 + 0.5*a9ans2)/(1+r[0]) -a11 )]
    out.append(((0.5 * math.log(y_u9/y_u8d) - df.Vol.iloc[10])))    
    return out

g = fsolve(bdtTen,[0.1,0.1],xtol=1.49012e-20)
r_u10 = g[0] * math.exp(20 * g[1]) 
r_u9d = g[0] * math.exp(18 * g[1]) 
r_u8d2 = g[0] * math.exp(16 * g[1])
r_u7d3 = g[0] * math.exp(14 * g[1])
r_u6d4 = g[0] * math.exp(12 * g[1])
r_u5d5 = g[0] * math.exp(10 * g[1])
r_u4d6 = g[0] * math.exp(8 * g[1])
r_u3d7 = g[0] * math.exp(6 * g[1])
r_u2d8 = g[0] * math.exp(4 * g[1])
r_ud9 = g[0] * math.exp(2 * g[1]) 
r_d10 = g[0]

In [19]:
N = 10
BDT_short_rate = np.zeros((N+1,N+1)) 
BDT_short_rate[0][:] = [0.1,r_d,r_d2,r_d3,r_d4,r_d5,r_d6,r_d7,r_d8,r_d9,r_d10] #t=0
BDT_short_rate[1][1:] =[r_u,r_ud,r_ud2,r_ud3,r_ud4,r_ud5,r_ud6,r_ud7,r_ud8,r_ud9] #t=1
BDT_short_rate[2][2:] = [r_u2,r_u2d,r_u2d2,r_u2d3,r_u2d4,r_u2d5,r_u2d6,r_u2d7,r_u2d8] #t=2
BDT_short_rate[3][3:] = [r_u3,r_u3d,r_u3d2,r_u3d3,r_u3d4,r_u3d5,r_u3d6,r_u3d7] #t=3
BDT_short_rate[4][4:] = [r_u4,r_u4d,r_u4d2,r_u4d3,r_u4d4,r_u4d5,r_u4d6] #t=4
BDT_short_rate[5][5:] = [r_u5,r_u5d,r_u5d2,r_u5d3,r_u5d4,r_u5d5] 
BDT_short_rate[6][6:] = [r_u6,r_u6d,r_u6d2,r_u6d3,r_u6d4] #t=6
BDT_short_rate[7][7:] = [r_u7,r_u7d,r_u7d2,r_u7d3] #t=7
BDT_short_rate[8][8:] = [r_u8,r_u8d,r_u8d2] #t=8
BDT_short_rate[9][9:] = [r_u9,r_u9d] #t=9
BDT_short_rate[10][10:] = [r_u10] #t=10   

print(BDT_short_rate)

[[0.1        0.08865046 0.08170213 0.07399991 0.07204519 0.06688605
  0.06869111 0.06515502 0.07060991 0.0679456  0.07792611]
 [0.         0.13225095 0.11743614 0.10593648 0.09953703 0.0919516
  0.09115208 0.08606306 0.0899423  0.08627749 0.09523192]
 [0.         0.         0.16879911 0.15165611 0.13751953 0.12641045
  0.12095747 0.11368041 0.11456772 0.10955536 0.11638099]
 [0.         0.         0.         0.21710724 0.18999585 0.17378276
  0.16050877 0.15016009 0.14593536 0.13911365 0.14222684]
 [0.         0.         0.         0.         0.26249668 0.23890784
  0.21299277 0.19834598 0.1858912  0.17664684 0.17381254]
 [0.         0.         0.         0.         0.         0.32843853
  0.28263826 0.26199457 0.2367866  0.22430658 0.21241277]
 [0.         0.         0.         0.         0.         0.
  0.3750568  0.34606779 0.30161671 0.28482502 0.25958533]
 [0.         0.         0.         0.         0.         0.
  0.         0.45711983 0.38419675 0.36167148 0.31723395]
 [0.     

In [20]:
Price = np.zeros((N+1,N+1))
for i in trange(len(Price)-1,-1,-1):
    for j in trange(len(Price)-1,-1,-1):
      if i > j :
          pass
      else:
          if j == N:
              Price[i][j] = price
          else:
              Price[i][j] = 100*c + (q*Price[i+1][j+1] + p*Price[i][j+1])/(1+BDT_short_rate[i][j])
print(Price)
Bond_Price = Price[0][0]
Callable_Bond_Price = round(Bond_Price - Call_Price,2)
print('Callable Bond Price = {}'.format(Callable_Bond_Price))

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████| 11/11 [00:00<?, ?it/s]

100%|█████████████████████████████████████████| 11/11 [00:00<00:00, 144.73it/s]

[[102.54298537 121.52541401 140.80234585 160.01127235 178.17202758
  195.60426035 211.28466069 226.28801926 239.37191806 252.46950762
  263.75      ]
 [  0.          91.9691538  111.81989562 132.70240022 153.71815642
  174.62017145 194.35450678 213.55245362 230.97501627 248.30168083
  263.75      ]
 [  0.           0.          83.9896676  104.90898784 127.63739361
  151.3225317  174.9875753  198.58552297 220.94115124 243.20783323
  263.75      ]
 [  0.           0.           0.          78.56831943 101.33254374
  126.54481061 153.52447186 181.39120327 209.12997938 237.03967082
  263.75      ]
 [  0.           0.           0.           0.          76.53141717
  101.53584755 130.63615156 162.17619313 195.47610641 229.65391799
  263.75      ]
 [  0.           0.           0.           0.           0.
   77.81800983 107.32297669 141.40230151 180.02846753 220.92806739
  263.75      ]
 [  0.           0.           0.           0.           0.
    0.          84.81708519 119.80179042 162.9874